# Generated by Django 4.2 on 2023-04-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domanda', models.CharField(max_length=255)),
                ('risposta', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2)),
                ('risposta_corretta', models.BooleanField(default=False)),
            ],
        ),
    ]
