# Generated by Django 4.2 on 2023-04-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qa',
            old_name='risposta_corretta',
            new_name='correct_answer',
        ),
        migrations.RenameField(
            model_name='qa',
            old_name='domanda',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='qa',
            name='risposta',
        ),
        migrations.AddField(
            model_name='qa',
            name='answer',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
