# Generated by Django 4.2 on 2023-04-28 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0003_remove_qa_correct_answer_alter_qa_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered_correctly', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='qa',
            name='answered_correctly',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='qa',
            name='answer',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2),
        ),
        migrations.AlterField(
            model_name='qa',
            name='question',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='CorrectAnswer',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.qa'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
